improvements

diff --git a/.github/workflows/download-playlist.yml b/.github/workflows/download-playlist.yml
--- a/.github/workflows/download-playlist.yml
+++ b/.github/workflows/download-playlist.yml
@@ -22,8 +22,14 @@ jobs:
 
       -
         uses: actions/checkout@v4
-        with:
-          lfs: true
+
+      -
+        name: Validate playlist exists
+        run: |
+          if [[ "$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name')" == "null" ]]; then
+            echo "::error::Unrecognized playlist: '${{ inputs.PLAYLIST }}'"
+            exit 1
+          fi
 
       -
         name: Parse playlist data
diff --git a/.github/workflows/generate-video.yml b/.github/workflows/generate-video.yml
--- a/.github/workflows/generate-video.yml
+++ b/.github/workflows/generate-video.yml
@@ -9,6 +9,11 @@ on:
     secrets:
       GH_PAT:
         required: true
+  workflow_dispatch:
+    inputs:
+      PLAYLIST:
+        type: string
+        required: true
 
 permissions:
   contents: read
@@ -27,6 +32,14 @@ jobs:
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.GH_PAT }}
+
+      -
+        name: Validate playlist exists
+        run: |
+          if [[ "$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name')" == "null" ]]; then
+            echo "::error::Unrecognized playlist: '${{ inputs.PLAYLIST }}'"
+            exit 1
+          fi
 
       -
         name: Parse playlist data
